### ISSUE TITLE
When running multiple commands error is only reported if the last command fails

### ISSUE THREAD

**Issue by mqasimsarfraz** [Azure/InnovationEngine#125]
When running multiple commands as part of a block, error is only reported if the last command fails. 

````
→ cat /tmp/test.md 
# Hello

```bash
doesnotexit
echo "Hello"
```
→ ie execute /tmp/test.md 
Hello
1. Hello
        
  ✔ doesnotexit
    echo "Hello"

  Hello

````

As you can see `doesnotexit` fails but the execution is marked successful. Perhaps there should be a way to do `set -e` for such blocks? 

### Usecase:

I was testing my README.md as part of CI and only found out the issue only once I moved the failing command to independent block.

- [ `kubectl krew install aks` should fail but works fine.](https://github.com/Azure/kubectl-aks/actions/runs/6696164677/job/18193470486#step:6:53)
- [`kubectl krew unistall aks` fails only because it is the last (only) command in code block. ](https://github.com/Azure/kubectl-aks/actions/runs/6696164677/job/18193470486#step:6:64)

**Comment by vmarcella** [comment]
This has been resolved in #155
