### ISSUE TITLE
Test using MS Learn docs as source

### ISSUE THREAD

**Issue by mbifeld** [Azure/InnovationEngine#133]
We have our own MS Learn repo [here](https://github.com/MicrosoftDocs/executable-docs)
which surfaces in MS Learn [here](https://review.learn.microsoft.com/en-us/azure/linux-workloads/?branch=live).

We should use this repo as source for automatic IE testing.

We will soon be using a secondary branch off of azure-docs-pr to host the files and localized versions too.  This will be source once created.

Note: The yaml files for AKS scenario need to be added.

**Comment by vmarcella** [comment]
Testing official documentation has been setup in the documentation repository and will no longer happen within this repository in the future.
