### ISSUE TITLE
Env variables are not set correctly for the 2. scenario

### ISSUE THREAD

**Issue by belginceran** [Azure/InnovationEngine#46]
Hello, 

I got an error when I tried to run  "Create a VM with a secure web server" scenario. 
Please see the screenshots below : 

![image](https://github.com/Azure/InnovationEngine/assets/110536035/7b07bfaa-5e75-4521-b60c-9cd40182684a)

![image](https://github.com/Azure/InnovationEngine/assets/110536035/483aff42-15ea-41ae-b574-67ea90c5d217)

Thanks

**Comment by vmarcella** [comment]
This was an issue with the CLI and it has been resolved. The scenario should no longer fail when setting up the environment variables.
