### ISSUE TITLE
no header found error on Scenario #3 

### ISSUE THREAD

**Issue by belginceran** [Azure/InnovationEngine#47]
Hello, 

I got " no header found " error when I was testing the "Create a LAMP stack on an Azure Linux VM" scenario. 
After the error it was like continuing with the next steps but actually it hung and did not create the resources. Uploaded 2 screenshots. 

![image](https://github.com/Azure/InnovationEngine/assets/110536035/6cc3844c-e598-42e7-bcc2-d8702f13bb79)

![image](https://github.com/Azure/InnovationEngine/assets/110536035/55fd66a0-4d67-49e0-8af5-e6d2730adb84)

Thanks

**Comment by vmarcella** [comment]
This is a known issue and should be resolved in an upcoming portal deployment.

**Comment by pjsingh28** [comment]
This issue is fixed pending a deployment

**Comment by vmarcella** [comment]
This has been deployed.
