### ISSUE TITLE
Breadcrumb keeps adding in the failed scenario if you click on 'Try again'

### ISSUE THREAD

**Issue by varundesai93** [Azure/InnovationEngine#48]
Breadcrumb keeps adding in the failed scenario if you click on 'Try again'
It also stores the previous sessions. 
<img width="492" alt="Screenshot 2023-09-25 140941" src="https://github.com/Azure/InnovationEngine/assets/38735764/5bdb4cf5-3fe0-4099-884b-df11eb701ef1">

**Comment by vmarcella** [comment]
#56

**Comment by pjsingh28** [comment]
We have addressed this and the solution will be part of an upcoming PR.
