### ISSUE TITLE
Directory switch when selecting a resource

### ISSUE THREAD

**Issue by mayasingh17** [Azure/InnovationEngine#49]
![image](https://github.com/Azure/InnovationEngine/assets/139000502/6de75a2e-13af-413b-8845-a22629deb7f2)
When I run the SSH Exec Doc everything is fine, in that I am running the doc from my Default Directory in Azure. However, when I click on the Disk resource on the left hand side and a new tab is opened, I for some reason get a 401 error that says Limited or No Access. "You are not a member of this tenant and do not have access to this directory or any subscriptions/resources within." In the upper right hand corner I can see my account is classified as a Restricted Tenant. If I exit and sign out and then sign back in again to the Azure portal, my default directory status is restored and I can even see the RG that was created from the Exec Docs. Please note: I am using the Visual Studio Enterprise Subscription so that may be part of the issue. I am using my personal account but it is linked to the VS subscription (per Azure Bootcamp instructions).

**Comment by mbifeld** [comment]
Issue is incorrect domain in links.

**Comment by mbifeld** [comment]
Duplicate as #50
