### ISSUE TITLE
Failed to SSH into Machine

### ISSUE THREAD

**Issue by rgardler-msft** [Azure/InnovationEngine#52]
Using the VM+SSH scenario, everything looked to progress well. The portal reported success, the script was at the stage of connecting:

![image](https://github.com/Azure/InnovationEngine/assets/108765066/9392930e-b58d-4413-8ed7-3b91e9fc4457)

After a period of time I got a connection timeout in cloudshell and the Portal switched to deployment failed.

![image](https://github.com/Azure/InnovationEngine/assets/108765066/96f741f6-59bf-40a1-8e2b-0814260efd18)

The "View Error Details" looks like a link but is not. There is a tooltiip:

![image](https://github.com/Azure/InnovationEngine/assets/108765066/e92a8d6f-7ecf-4cfe-a0f8-ae90c7294163)

Subscription is Ross Dev Account. Time of deployment circa 3:06pm

**Comment by vmarcella** [comment]
This connection timing out indicates that the resources are available but that the virtual machine isn't accessible. Is the resource still alive and do you know it started successfully?

**Comment by pjsingh28** [comment]
This is a issue that we cannot really do anything about. The portal behavior here is correct in the sense that all script commands did not succeed. This error does happen but is not frequent
