### ISSUE TITLE
VM + SSH failure: Changing public keys not allowed

### ISSUE THREAD

**Issue by rgardler-msft** [Azure/InnovationEngine#53]
Using the VM + SSH (immediately after the failure reported in #52 I clicked the "Try Again" button and then the VM + SSH option again) I got the following error:

![image](https://github.com/Azure/InnovationEngine/assets/108765066/792ede3e-f8df-4b46-b31e-170c5c5b5029)

**Comment by rgardler-msft** [comment]
I got this on another deployment too. I think the problem is in the "Unique" postfix not being Unique (or even close):

![image](https://github.com/Azure/InnovationEngine/assets/108765066/c2e1e83c-4056-4593-b552-28ee79177735)

Pretty much every possible number here is taken in my  subscription.

Suggest using `$(date +%s)$$` instead (which still isn't 100% unique). For truly unique we need `$(uuidgen)`

**Comment by vmarcella** [comment]
I increased the random postfix from 100 -> 100,000 as that should provide enough entropy while also allowing the resource names to remain at a reasonable length.

**Comment by rgardler-msft** [comment]
If the length is the concern then I propose using `postfix=$(date +%M%S)$$`

This is only one more digit than 100000 but is more likely to be unique (it is minutes, seconds and process ID).

**Comment by vmarcella** [comment]
This has been fixed and the issue will be resolved once this merges into main.
