### ISSUE TITLE
400 in Create VM with Secure Web Server

### ISSUE THREAD

**Issue by rgardler-msft** [Azure/InnovationEngine#55]
I think this is a known issue, but for completeness.

![image](https://github.com/Azure/InnovationEngine/assets/108765066/68d95e0f-a618-483c-b5ed-f534f23a0c33)

**Comment by mbifeld** [comment]
This is the issue that is dependent on the Cloud Shell team.  We are in discussion with their Eng and PM teams.

**Comment by mbifeld** [comment]
Note that this is no longer a CloudShell issue.  We need tokens that are not standard in the base Cloud Shell.  These are usually passed in via whatever blade/experience needs it, however we currently do not have the elevated permissions for this.  We are escalating with the permissions team.

**Comment by mbifeld** [comment]
PJ has escalated, but approval process from other teams is slow.  PJ has created a proposal for CloudShell adopting our React component.

**Comment by mbifeld** [comment]
Ticket for graph permissions is cancelled for now as little progress is expected.  However, the permissions to solve this specific issue (Key Vault) are still expected to be fixed.

**Comment by mbifeld** [comment]
Issue moved to private board
