### ISSUE TITLE
Breadcrumbs not resetting when hitting "Try Again"

### ISSUE THREAD

**Issue by rgardler-msft** [Azure/InnovationEngine#56]
I have tried a few failed deployments now, each time I hit "Try Again" and am taken back to the selection screen. The breadcrumbs are not resetting:

![image](https://github.com/Azure/InnovationEngine/assets/108765066/e504b196-9056-4938-9af1-8f4c4b180555)

**Comment by pjsingh28** [comment]
We have addressed this and the solution will be part of an upcoming PR.
