### ISSUE TITLE
Error Creating Scenrio:  no header found

### ISSUE THREAD

**Issue by rgardler-msft** [Azure/InnovationEngine#59]
![image](https://github.com/Azure/InnovationEngine/assets/108765066/34222ac7-6985-48ed-a8cb-c2f0946c969f)

Note that the shell has returned the portal is stuck in the Initializing stage (not reporting error)

RossDev subscription. Deployment time : 5:26pm (PT)

**Comment by vmarcella** [comment]
This will be fixed in an upcoming portal deployment. #47

**Comment by vmarcella** [comment]
This has been deployed.
