### ISSUE TITLE
Improve random suffix creation for resource names

### ISSUE THREAD

**Issue by mbifeld** [Azure/InnovationEngine#79]
Per Aaron:

[Yesterday 3:55 PM] Aaron Wislang

Though unlikely to have a collision, I wondered about using: 

export UNIQUE_POSTFIX="$(date +%M%S)$$"

for the random suffixes especially if they're used for an FQDN that needs to be globally unique. 

 

You might have a room full of people you ask to go through the steps with you and if they click at the same time it might collide.

 

One thing I've done in the past is feed the fully qualified scope of the current resource group to shasum to get a 6 character, globally unique, string you can use anywhere. Also helps if you want to be able to re-run the script.

 

https://github.com/Azure-Samples/azure-opensource-labs/blob/fe4fbe9ba454d7de1a180f82d7c68917316bb17f/cloud-native/containerapps-python-fastapi/README.md?plain=1#L44

 

We do the same thing in bicep, via var rand = substring(uniqueString(resourceGroup().id), 0, 6)(https://github.com/Azure-Samples/azure-opensource-labs/blob/main/cloud-native/aks-bicep-k8s/aks.bicep )

 

It's handy if you want to be able to have a Container Registry, a Storage Account, etc, with the same suffix.

 

A smaller suffix is also easier on the eyes.

**Comment by vmarcella** [comment]
If still an active problem, this issue should be reopened within the executable docs repo here as the random suffixes are set in the docs and not by ie.
