### ISSUE TITLE
Setup and communicate ICM / escalation team information for Innovation Engine

### ISSUE THREAD

**Issue by mbifeld** [Azure/InnovationEngine#89]

**Comment by vmarcella** [comment]
@mbifeld What service/org would this fall under? I don't think the innovation engine is owned by AzTux (My org) and I don't have the ability to create an IcM escalation team. 

Do we also have examples of issues that would need to be escalated for CLI issues? The innovation engine isn't a service and doesn't operate under the same conditions as one, so I'm curious as to what type of incidents we'd be using it for.

**Comment by mbifeld** [comment]
@vmarcella Rahul was also confused on the details of this task.  I will bring this up Monday to ask Arun for more details on what he was intending.
