### ISSUE TITLE
Make sure every new scenario added has the right level of testing across Portal and Innovation Engine.

### ISSUE THREAD

**Issue by mbifeld** [Azure/InnovationEngine#92]

**Comment by vmarcella** [comment]
All scenarios added to the Innovation Engine will automatically be added to our scenario testing pipeline and will be subjected to the same level of testing as other scenarios.

**Comment by mbifeld** [comment]
Need to test newer IE builds on Portal via selecting IE version

**Comment by mbifeld** [comment]
[#122](https://github.com/Azure/InnovationEngine/issues/122)

**Comment by mbifeld** [comment]
Issue moved to private board
